name: name_of_sweep
entity: your_wb_entitiy
project: your_wb_project
program: dummy
method: grid
metric:
  name: val_err
  goal: minimize
parameters:  # total 65 jobs
  lr:  # sample this lrs
    values: [1E-5, 5E-5, 1E-4, 5E-4, 1E-3]
  subsample: # subsample downstream dataset by this amount
    values: [1, 2, 4, 8, 16, 32, 64, 128, 256, 512, 1024, 2048, 4096]
  plot_figs: # dont plot figs in W&b
    value: !!bool False
